version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '4000:4000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - database
    depends_on:
      - database
  database:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: pokeapi
      POSTGRES_PASSWORD: pokeapi
      POSTGRES_DB: pokeapi
    ports:
      - '5432:5432'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
